package utils

object Constants {
    const val MAIN_NAVIGATION_BACKGROUND_COLOR = 0xFF183354
    const val MAIN_NAVIGATION_ACTIVE_TEXT_ICON_COLOR = 0xFFDFDFDF
    const val MAIN_NAVIGATION_INACTIVE_TEXT_ICON_COLOR = 0xFF545E69
}
